export enum Instruction {
    ADD,
    SUB,
    MUL,
    DIV,
    MOD,
    NOT,
    INF,
    INFEQ,
    SUP,
    SUPEQ,
    FADD,
    FSUB,
    FMUL,
    FDIV,
    FCOS,
    FSIN,
    FINF,
    FINFEQ,
    FSUP,
    FSUPEQ,
    PADD,
    CONCAT,
    CHRCODE,
    STRLEN,
    CHARAT,
    ALLOC,
    ALLOCN,
    FREE,
    POPST,
    EQUAL,
    ATOI,
    ATOF,
    ITOF,
    FTOI,
    STRI,
    STRF,
    PUSHI,
    PUSHN,
    PUSHF,
    PUSHS,
    PUSHG,
    PUSHL,
    PUSHSP,
    PUSHFP,
    PUSHGP,
    PUSHST,
    LOAD,
    LOADN,
    DUP,
    DUPN,
    COPY,
    COPYN,
    POP,
    POPN,
    STOREL,
    STOREG,
    STORE,
    STOREN,
    CHECK,
    SWAP,
    AND,
    OR,
    WRITEI,
    WRITEF,
    WRITES,
    WRITELN,
    WRITECHR,
    READ,
    PUSHA,
    JUMP,
    JZ,
    CALL,
    RETURN,
    START,
    NOP,
    ERR,
    STOP,
}

const instructionHasSideEffects = new Set<Instruction>([
    Instruction.WRITEI,
    Instruction.WRITEF,
    Instruction.WRITES,
    Instruction.WRITELN,
    Instruction.WRITECHR,
    Instruction.READ,
])

export function hasSideEffects(instruction: Instruction): Boolean {
    return instructionHasSideEffects.has(instruction)
}

export type InstructionArgTypes = "int" | "float" | "string" | "label"

const instructionArgTypes: Partial<Record<Instruction, InstructionArgTypes[]>> = {
    [Instruction.ALLOC]: ["int"],
    [Instruction.PUSHI]: ["int"],
    [Instruction.PUSHN]: ["int"],
    [Instruction.PUSHF]: ["float"],
    [Instruction.PUSHS]: ["string"],
    [Instruction.PUSHG]: ["int"],
    [Instruction.PUSHL]: ["int"],
    [Instruction.PUSHST]: ["int"],
    [Instruction.LOAD]: ["int"],
    [Instruction.DUP]: ["int"],
    [Instruction.COPY]: ["int"],
    [Instruction.POP]: ["int"],
    [Instruction.STOREL]: ["int"],
    [Instruction.STOREG]: ["int"],
    [Instruction.STORE]: ["int"],
    [Instruction.CHECK]: ["int", "int"],
    [Instruction.PUSHA]: ["label"],
    [Instruction.JUMP]: ["label"],
    [Instruction.JZ]: ["label"],
    [Instruction.ERR]: ["string"],
}

export function getInstructionArgTypes(instruction: Instruction): InstructionArgTypes[] {
    return instructionArgTypes[instruction] ?? []
}

export const InstructionDocumentation: Record<Instruction, string> = {
    [Instruction.ADD]: "takes n and m from the pile and stacks the result m + n",
    [Instruction.SUB]: "takes n and m from the pile and stacks the result m - n",
    [Instruction.MUL]: "takes n and m from the pile and stacks the result m x n",
    [Instruction.DIV]: "takes n and m from the pile and stacks the result m / n",
    [Instruction.MOD]: "takes n and m from the pile and stacks the result m mod n",
    [Instruction.NOT]: "takes n from the pile and stacks the result n = 0",
    [Instruction.INF]: "takes n and m from the pile and stacks the result m < n",
    [Instruction.INFEQ]: "takes n and m from the pile and stacks the result m <= n",
    [Instruction.SUP]: "takes n and m from the pile and stacks the result m > n",
    [Instruction.SUPEQ]: "takes n and m from the pile and stacks the result m >= n",
    [Instruction.FADD]: "takes n and m from the pile and stacks the result m + n",
    [Instruction.FSUB]: "takes n and m from the pile and stacks the result m - n",
    [Instruction.FMUL]: "takes n and m from the pile and stacks the result m x n",
    [Instruction.FDIV]: "takes n and m from the pile and stacks the result m / n",
    [Instruction.FCOS]: "takes n from the pile and stacks the result cos(n)",
    [Instruction.FSIN]: "takes n from the pile and stacks the result sin(n)",
    [Instruction.FINF]: "takes n and m from the pile and stacks the result m < n",
    [Instruction.FINFEQ]: "takes n and m from the pile and stacks the result m <= n",
    [Instruction.FSUP]: "takes n and m from the pile and stacks the result m > n",
    [Instruction.FSUPEQ]: "takes n and m from the pile and stacks the result m >= n",
    [Instruction.PADD]: "takes an Integer n and an address a from the pile and stacks the address a + n",
    [Instruction.CONCAT]: "takes n and m, from the pile and stacks the concatenated strings (string ns + string ms) address",
    [Instruction.CHRCODE]: "takes n from the pile, which must be a string, and stacks the ASCII code from the first character",
    [Instruction.STRLEN]: "takes n, from the pile and stacks the size of the string",
    [Instruction.CHARAT]: "takes n and m, from the pile and stacks the ASCII code from the character in the string m at the position n",
    [Instruction.ALLOC]: "integer_n :: allocates a structured block, sized n, and stacks its address",
    [Instruction.ALLOCN]: "takes an integer n from the pile and allocates a structured block, sized n, and stacks its address",
    [Instruction.FREE]: "takes an address a from the pile and frees its allocated structured block",
    [Instruction.POPST]: "removes the last structured block from the heap",
    [Instruction.EQUAL]: "takes n and m from the pile and stacks the result n = m",
    [Instruction.ATOI]: "takes a String Heap address from the pile and stacks its string's conversion to an integer (it fails if the string doesn't represent an integer)",
    [Instruction.ATOF]: "takes a String Heap address from the pile and stacks its string's conversion to a real number (it fails if the string doesn't represent a real number)",
    [Instruction.ITOF]: "takes an integer from the pile and stacks its conversion to a real number",
    [Instruction.FTOI]: "takes a real number from the pile and stacks its conversion to a whole number - by removing its decimals",
    [Instruction.STRI]: "takes an integer from the pile, converts it to a string and stacks its address",
    [Instruction.STRF]: "takes a real number from the pile, converts it to a string and stacks its address",
    [Instruction.PUSHI]: "integer_n :: stacks n",
    [Instruction.PUSHN]: "integer_n :: stacks n times the integer 0",
    [Instruction.PUSHF]: "real_number_n :: stacks n",
    [Instruction.PUSHS]: "string_n :: archives s in the String Heap and stacks its address",
    [Instruction.PUSHG]: "integer_n :: stacks the value found in gp[n]",
    [Instruction.PUSHL]: "integer_n :: stacks the value found in fp[n]",
    [Instruction.PUSHSP]: "stacks the value of the register sp",
    [Instruction.PUSHFP]: "stacks the value of the register fp",
    [Instruction.PUSHGP]: "stacks the value of the register gp",
    [Instruction.PUSHST]: "integer_n :: pushes the address of the struct heap at index n to the stack",
    [Instruction.LOAD]: "integer_n :: takes an address a from the pile and stacks the value found in a[n] in the pile or in the heap (depending on a)",
    [Instruction.LOADN]: "takes an integer n and an address a from the pile and stacks the value found in a[n] in the pile or in the heap (depending on a)",
    [Instruction.DUP]: "integer_n :: duplicates and stacks n times the value of the top of the pile",
    [Instruction.DUPN]: "takes the integer n from the pile and duplicates and stacks n times the value of the top of the pile",
    [Instruction.COPY]: "integer_n :: copies the n values of the top of the pile and stacks them in the same order",
    [Instruction.COPYN]: "takes the integer n from the pile and copies and stacks the n values of the top of the pile in the same order",
    [Instruction.POP]: "integer_n :: takes n values from the pile",
    [Instruction.POPN]: "takes the integer n from the pile and takes n values m from the pile",
    [Instruction.STOREL]: "integer_n :: takes a value from the pile and stores it in fp[n]",
    [Instruction.STOREG]: "integer_n :: takes a value from the pile and stores it in gp[n]",
    [Instruction.STORE]: "integer_n :: takes a value v and an address a and stores v in a[n] in the pile or the heap (depending on a)",
    [Instruction.STOREN]: "takes a value v, an integer n and an address a and stores v in a[n] in the pile or the heap (depending on a)",
    [Instruction.CHECK]: "integer_n , integer_p :: checks that at the top of the pile there's an integer i such that n <= i <= p (it throws an error if this is false)",
    [Instruction.SWAP]: "takes the values v and m from the pile and stacks m followed by n",
    [Instruction.AND]: "takes n and m from the pile and stacks the result n && m",
    [Instruction.OR]: "takes n and m from the pile and stacks the result n || m",
    [Instruction.WRITEI]: "takes an integer from the pile and prints its value",
    [Instruction.WRITEF]: "takes a real number from the pile and prints its value",
    [Instruction.WRITES]: "takes a String Heap address from the pile and prints its string",
    [Instruction.WRITELN]: "prints \\n",
    [Instruction.WRITECHR]: "takes an integer from the pile and prints its corresponding ASCII character",
    [Instruction.READ]: "reads a string from the keyboard, stores it in the String Heap and stacks its address",
    [Instruction.PUSHA]: "label :: stacks label's code address",
    [Instruction.JUMP]: "label :: assigns the label's code address to the register pc ",
    [Instruction.JZ]: "label :: takes a value v from the pile and if:\nv = 0, assigns the label's code address to the register pc\n v != 0, increments register pc by 1",
    [Instruction.CALL]: "takes an label's address a from the pile, saves pc and fp in the Call Stack and assigns a to pc and the current sp's value to fp.",
    [Instruction.RETURN]: "assigns the current fp's value to sp, reinstates the values fp and pc from the Call Stack and increments pc by 1",
    [Instruction.START]: "assigns sp's value to fp",
    [Instruction.NOP]: "doesn't do anything",
    [Instruction.ERR]: "string_x :: throws an error with message x",
    [Instruction.STOP]: "stops program execution",
}
